[repository]
name = "hyfocus"
url = "git@github.com:ernestoCruz05/hyfocus.git"
authors = ["faky (github.com/ernestoCruz05)"]
commit_pins = []

[hyfocus]
description = "A Pomodoro focus enforcement plugin that locks workspaces and blocks app launches during focus sessions"
authors = ["faky (github.com/ernestoCruz05)"]
output = "build/libhyfocus.so"
build = [
    "cmake -DCMAKE_BUILD_TYPE=Release -B build",
    "cmake --build build",
]
